description "Litonpay Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env LITONPAYD_BIN="/usr/bin/litonpayd"
env LITONPAYD_USER="litonpay"
env LITONPAYD_GROUP="litonpay"
env LITONPAYD_PIDDIR="/var/run/litonpayd"
# upstart can't handle variables constructed with other variables
env LITONPAYD_PIDFILE="/var/run/litonpayd/litonpayd.pid"
env LITONPAYD_CONFIGFILE="/etc/litonpay/litonpay.conf"
env LITONPAYD_DATADIR="/var/lib/litonpayd"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # litonpayd will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$LITONPAYD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run litonpayd."
        echo "The setting must appear in $LITONPAYD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following"
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is also recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Litonpay Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$LITONPAYD_PIDDIR"
    chmod 0755 "$LITONPAYD_PIDDIR"
    chown $LITONPAYD_USER:$LITONPAYD_GROUP "$LITONPAYD_PIDDIR"
    chown $LITONPAYD_USER:$LITONPAYD_GROUP "$LITONPAYD_CONFIGFILE"
    chmod 0660 "$LITONPAYD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$LITONPAYD_PIDFILE" \
    --chuid $LITONPAYD_USER:$LITONPAYD_GROUP \
    --exec "$LITONPAYD_BIN" \
    -- \
    -pid="$LITONPAYD_PIDFILE" \
    -conf="$LITONPAYD_CONFIGFILE" \
    -datadir="$LITONPAYD_DATADIR" \
    -disablewallet \
    -daemon

